# compose/git.yml — Forgejo v9: Git server local (remplace GitHub pour les apps Frappe)

volumes:
  forgejo_data:
    name: ${PREFIX}forgejo_data
  forgejo_repos:
    name: ${PREFIX}forgejo_repos

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:9
    container_name: ${PREFIX}forgejo
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000
      FORGEJO__database__DB_TYPE: sqlite3
      FORGEJO__database__PATH: /data/gitea/forgejo.db
      FORGEJO__server__DOMAIN: git.${DOMAIN}
      FORGEJO__server__ROOT_URL: https://git.${DOMAIN}/
      FORGEJO__server__SSH_PORT: ${PORT_FORGEJO_SSH}
      FORGEJO__server__SSH_LISTEN_PORT: 2222
      FORGEJO__server__START_SSH_SERVER: "true"
      FORGEJO__security__INSTALL_LOCK: "true"
      FORGEJO__service__DISABLE_REGISTRATION: "false"
      FORGEJO__log__LEVEL: warn
    volumes:
      - forgejo_data:/data
      - forgejo_repos:/data/git/repositories
    ports:
      - "127.0.0.1:${PORT_FORGEJO_HTTP}:3000"
      - "127.0.0.1:${PORT_FORGEJO_SSH}:2222"
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.forgejo.rule=Host(`git.${DOMAIN}`)"
      - "traefik.http.routers.forgejo.entrypoints=websecure"
      - "traefik.http.routers.forgejo.tls=true"
      - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
