# compose/press.yml — Frappe Press: Dashboard SaaS
# NOTE volumes: montage sur /home/frappe (parent), pas /home/frappe/frappe-bench
# Docker copie l'image dans le volume → bench init peut créer le sous-répertoire

volumes:
  press_home:
    name: ${PREFIX}press_home

services:
  press:
    build:
      context: ../docker/press
      dockerfile: Dockerfile
    image: ${PREFIX}press:latest
    container_name: ${PREFIX}press
    restart: unless-stopped
    volumes:
      - press_home:/home/frappe
      - ../data/ssh:/home/frappe/.ssh:ro
      - ../apps/press_patches:/home/frappe/press_patches:ro
    ports:
      - "127.0.0.1:${PORT_PRESS}:8000"
    networks:
      - default
    environment:
      SITE_NAME: ${PRESS_SITE_NAME}
      ADMIN_PASSWORD: ${PRESS_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${PRESS_ADMIN_EMAIL}
      DB_HOST: ${PREFIX}mariadb
      DB_PORT: 3306
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      REDIS_CACHE_URL: redis://${PREFIX}redis_cache:6379
      REDIS_QUEUE_URL: redis://${PREFIX}redis_queue:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.press.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.press.entrypoints=websecure"
      - "traefik.http.routers.press.tls=true"
      - "traefik.http.services.press.loadbalancer.server.port=8000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:8000/api/method/ping"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 300s
